geodjango/urls.py
from django.contrib import admin
from django.urls import path , include 

urlpatterns = [
    path('', include('weather_info.urls')),
    path('admin/', admin.site.urls),
]

weather_info/urls.py
from . import views
from django.conf.urls import  url
from django.urls import include, path
from django.views.generic import TemplateView
from djgeojson.views import GeoJSONLayerView
from .models import WeatherData

app_name = "weather_info"

urlpatterns = [
    path('date/', views.current_datetime, name="current_datetime"), #to add home page urls
    path('', views.WeatherApi.as_view(), name="weather_api"),
    path('weather-data', views.weather_data, name="weather_data"),
    path('update-data-on-map', views.add_data_on_map, name="update_data_on_map"),
    path('data/', views.dataset, name='data')
]

weather_info/models.py
from django.db import models as normal_models
# Create your models here.
from django.contrib.gis.db import models


class WeatherLatLong(models.Model):
    name = models.CharField(max_length=100)
    location = models.PointField()
    temperature = models.FloatField()
    humidity = models.FloatField()
    
    def __str__(self):
        return self.name
    
    def __unicode__(self):
        return self.name
    
    
class WeatherData(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    latitude = models.FloatField()
    longitude = models.FloatField()
    point = models.PointField()
    

weather_info/views.py
from django.shortcuts import render,HttpResponse,HttpResponseRedirect
import datetime
import requests
import json
from django.contrib.gis.geos import Polygon, Point
from django.core.serializers import serialize
from django.views.generic.base import TemplateView
from django.conf import settings as conf_settings
# Create your views here.
from .models import WeatherLatLong,WeatherData

OPEN_WEATHER_MAP_API_KEY = conf_settings.OPEN_WEATHER_MAP_API_KEY


def current_datetime(request):
    now = datetime.datetime.now()
    html = "<html><body>It is now %s.</body></html>" % now
    return HttpResponse(html)
 

class WeatherApi(TemplateView):
    template_name = 'home/index.html'

    def get_context_data(self, *args, **kwargs):
        context = super(WeatherApi, self).get_context_data(*args, **kwargs)
        context['message'] = ''
        return context


def dataset(request):
    weather = serialize('geojson', WeatherLatLong.objects.all())
    return HttpResponse(weather)


def weather_data(request):
    with open('static/city.list.json') as f:
        data = json.load(f)
        for row in data:
            id = row.get('id')
            name = row.get('name')
            state = row.get('state')
            country =  row.get('country')
            lat =  row['coord'].get('lat')
            lon =  row['coord'].get('lon')
            point = Point(lon, lat,srid=4326)
            WeatherData(id=id,name=name,state=state,country=country,latitude=lat, longitude=lon,point=point).save()
    return HttpResponse('successfully saved')

def add_data_on_map(request):
    message = ''
    if 'add' in request.POST:
        city = request.POST.get('city')
        data_out = WeatherLatLong.objects.filter(name__icontains=city).first()
        if data_out:
            message = "This place is already pointing on map"
        else:
            data = WeatherData.objects.filter(name__icontains=city).first()
            if data:
                latitude = data.latitude
                longitude = data.longitude
                point = Point(longitude, latitude)
                url = "http://api.openweathermap.org/data/2.5/weather?lat={}&lon={}&appid={}".format(latitude,longitude,OPEN_WEATHER_MAP_API_KEY)
                url_data =  requests.get(url)
                if url_data.status_code == 200:
                    temperature = url_data.json()['main'].get('temp')
                    humidity = url_data.json()['main'].get('humidity')
                    WeatherLatLong(name=city,location=point,temperature=temperature,humidity=humidity).save()
                else:
                    message = "openweathermap api response is ".format(url_data.status_code)
            else:
                message = "This place is not available on our database"
    elif 'delete' in request.POST:
        city = request.POST.get('city')
        data_out = WeatherLatLong.objects.filter(name__icontains=city).first()
        if data_out:
            id = data_out.id
            WeatherLatLong.objects.get(id=id).delete()
            message = '{}  mark has been removed from map'.format(city)
        else:
            message = 'Please provide valid place name to delete mark from map'
        
    return render(request,'home/index.html',{'message':message})
        

weather_info/templates/home/index.html
{% load leaflet_tags %}
<html>
  <head>
  	{% load static %}
    {% leaflet_js %}
    {% leaflet_css %}
	<title>GeoDjango</title>
	<style type="text/css">
		#gis {width:80%; height:600px}
	</style>
	<script type="text/javascript" src="{% static 'dist/leaflet.ajax.js' %}"></script>

  </head>
  <body>
    <h1>Temperature and Humidity info on Map</h1>
    <h5>Please tap on location symbols on below map to know temperature and humidity of a particular place</h5>
    <div>
		<form action="/update-data-on-map" method="post">
			{% csrf_token %}
			<div>
   			 	<label for="city">Enter city/state/country to mark/delete location on below Map: </label>
    		 	<input id="city" type="text" name="city" value="">
    		 	<input type="submit" name="add" value="ADD">
    		 	<input type="submit" name="delete" value="DELETE">
    		 </div>
		</form>
		<p style="color:red;">{{ message }}</p>
    </div>
	<script type="text/javascript">
		function out_layers(map,options){
			var datasets = new L.GeoJSON.AJAX("{% url 'weather_info:data' %}",{
				onEachFeature: function(feature,layer){
					temperature = feature.properties.temperature;
					temperature_in_celsius = (temperature-273.15).toFixed(2);
					layer.bindPopup("<b>"+feature.properties.name.toString()+"</b>"+'</br>'
							+"Temperature:"+temperature_in_celsius.toString()+"\u00B0C"+'</br>'
							+'Humidity:'+feature.properties.humidity.toString(),{ autoClose: false, closeOnClick: false });
				}
			});
			window.console.log(datasets)
			datasets.addTo(map);
		}
	</script>    

	{% leaflet_map "gis"  callback="window.out_layers" %}
  </body>
</html>